name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  pdm-dependencies:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pdm-project/setup-pdm@v3
      - name: install dependencies
        run: pdm install -dG documentation
  build-docs:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout main
        uses: actions/checkout@v2
      - name: build docs
        uses: moonpathbg/mkdocs_builder@latest

      # - name: Deploy docs
      #   uses: mhausenblas/mkdocs-deploy-gh-pages@nomaterial
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
